### ISSUE TITLE
Small UI text issue

### ISSUE THREAD

**Issue by propagare** [leigholiver/OBS-SC2Switcher#1]
In my case, the text description has been cut off. 

https://imgur.com/gallery/gFQ7c

**Comment by leigholiver** [comment]
What are you using for that dark mode? Based on the screenshot it looks like its made the separator way taller than it should be?

**Comment by propagare** [comment]
No special need. I tested it with all three OBS themes.

**Comment by propagare** [comment]
OT: Here are all 19 triggers (all scene possibilities) from the two local API endpoints as well as we could need a field where I could insert my in game Name (no ID) (max length: 12) to parse if I am a Player or an Observer IN GAME:


Set (automaticly) my race but NO detection for race in RANDOM! --> Define Random separately!
Scene definied by opponent races (exclude separately Random) -->  Set Scene?!

Via http://localhost:6119/ui
(prio 1)


Startup, loading and leaving Sc2: 
{'activeScreens': ['ScreenLoading/ScreenLoading']} 

Login screen (name, region, password, offline): 
 {'activeScreens': ['ScreenBackgroundSC2/ScreenBackgroundSC2', 'ScreenLoginSC2/ScreenLoginSC2', 'ScreenNavigationSC2/ScreenNavigationSC2', 'ScreenForegroundSC2/ScreenForegroundSC2', 'ScreenBattlenet/ScreenBattlenet']} 

In menu after Login (Home screen): 
{'activeScreens': ['ScreenBackgroundSC2/ScreenBackgroundSC2', 'ScreenHome/ScreenHome', 'ScreenNavigationSC2/ScreenNavigationSC2', 'ScreenForegroundSC2/ScreenForegroundSC2', 'ScreenBattlenet/ScreenBattlenet']}

Campaign screen:
{'activeScreens': ['ScreenBackgroundSC2/ScreenBackgroundSC2', 'ScreenSingle/ScreenSingle', 'ScreenNavigationSC2/ScreenNavigationSC2', 'ScreenForegroundSC2/ScreenForegroundSC2', 'ScreenBattlenet/ScreenBattlenet']}

Coop screen:
{'activeScreens': ['ScreenBackgroundSC2/ScreenBackgroundSC2', 'ScreenCoopCampaign/ScreenCoopCampaign', 'ScreenNavigationSC2/ScreenNavigationSC2', 'ScreenForegroundSC2/ScreenForegroundSC2', 'ScreenBattlenet/ScreenBattlenet']}

Custom Games main screen:
{'activeScreens': ['ScreenBackgroundSC2/ScreenBackgroundSC2', 'ScreenNavigationSC2/ScreenNavigationSC2', 'ScreenForegroundSC2/ScreenForegroundSC2', 'ScreenMultiplayer/ScreenMultiplayer', 'ScreenCustomGames/ScreenCustomGames', 'ScreenBattlenet/ScreenBattlenet']}

Multiplayer: Training, Versus AI, Unranked, Ranked and Testing (Ranked ladder screen): 
{'activeScreens': ['ScreenBackgroundSC2/ScreenBackgroundSC2', 'ScreenNavigationSC2/ScreenNavigationSC2', 'ScreenForegroundSC2/ScreenForegroundSC2', 'ScreenMultiplayer/ScreenMultiplayer', 'ScreenMatchmaking/ScreenMatchmaking', 'ScreenBattlenet/ScreenBattlenet']}

Tournament screen:
{'activeScreens': ['ScreenBackgroundSC2/ScreenBackgroundSC2', 'ScreenNavigationSC2/ScreenNavigationSC2', 'ScreenForegroundSC2/ScreenForegroundSC2', 'ScreenTournament/ScreenTournament', 'ScreenMultiplayer/ScreenMultiplayer', 'ScreenBattlenet/ScreenBattlenet']}

Custom game Lobby:
{'activeScreens': ['ScreenBackgroundSC2/ScreenBackgroundSC2', 'ScreenNavigationSC2/ScreenNavigationSC2', 'ScreenForegroundSC2/ScreenForegroundSC2', 'ScreenMultiplayer/ScreenMultiplayer', 'ScreenCustomGames/ScreenCustomGames', 'ScreenBattlenet/ScreenBattlenet', 'ScreenBattleLobby/ScreenBattleLobby']}

Arcade screen (join):
{'activeScreens': ['ScreenBackgroundSC2/ScreenBackgroundSC2', 'ScreenNavigationSC2/ScreenNavigationSC2', 'ScreenForegroundSC2/ScreenForegroundSC2', 'ScreenArcade/ScreenArcade', 'ScreenArcadeJoin/ScreenArcadeJoin', 'ScreenBattlenet/ScreenBattlenet']}

Arcade screen (browse):
{'activeScreens': ['ScreenBackgroundSC2/ScreenBackgroundSC2', 'ScreenNavigationSC2/ScreenNavigationSC2', 'ScreenForegroundSC2/ScreenForegroundSC2', 'ScreenArcade/ScreenArcade', 'ScreenArcadeBrowse/ScreenArcadeBrowse', 'ScreenBattlenet/ScreenBattlenet']}

Arcade game Lobby:
{'activeScreens': ['ScreenBackgroundSC2/ScreenBackgroundSC2', 'ScreenNavigationSC2/ScreenNavigationSC2', 'ScreenForegroundSC2/ScreenForegroundSC2', 'ScreenArcade/ScreenArcade', 'ScreenArcadeJoin/ScreenArcadeJoin', 'ScreenBattlenet/ScreenBattlenet', 'ScreenBattleLobby/ScreenBattleLobby']}

Collection screen:
{'activeScreens': ['ScreenBackgroundSC2/ScreenBackgroundSC2', 'ScreenNavigationSC2/ScreenNavigationSC2', 'ScreenForegroundSC2/ScreenForegroundSC2', 'ScreenBattlenet/ScreenBattlenet', 'ScreenCollection/ScreenCollection']}

Replay browsing:
{'activeScreens': ['ScreenBackgroundSC2/ScreenBackgroundSC2', 'ScreenReplay/ScreenReplay', 'ScreenNavigationSC2/ScreenNavigationSC2', 'ScreenForegroundSC2/ScreenForegroundSC2', 'ScreenBattlenet/ScreenBattlenet']}

Replay "Watch With Others" Lobby:
{'activeScreens': ['ScreenBackgroundSC2/ScreenBackgroundSC2', 'ScreenReplay/ScreenReplay', 'ScreenNavigationSC2/ScreenNavigationSC2', 'ScreenForegroundSC2/ScreenForegroundSC2', 'ScreenBattlenet/ScreenBattlenet', 'ScreenBattleLobby/ScreenBattleLobby']}

In Game:
{'activeScreens': []}

Score screen after a Custom game:
{'activeScreens': ['ScreenBackgroundSC2/ScreenBackgroundSC2', 'ScreenNavigationSC2/ScreenNavigationSC2', 'ScreenForegroundSC2/ScreenForegroundSC2', 'ScreenMultiplayer/ScreenMultiplayer', 'ScreenCustomGames/ScreenCustomGames', 'ScreenBattlenet/ScreenBattlenet', 'ScreenScore/ScreenScore']}

Score screen after a Multiplayer Ranked:
{'activeScreens': ['ScreenBackgroundSC2/ScreenBackgroundSC2', 'ScreenNavigationSC2/ScreenNavigationSC2', 'ScreenForegroundSC2/ScreenForegroundSC2', 'ScreenMultiplayer/ScreenMultiplayer', 'ScreenMatchmaking/ScreenMatchmaking', 'ScreenBattlenet/ScreenBattlenet', 'ScreenScore/ScreenScore']}

Score screen after Arcade:
{'activeScreens': ['ScreenBackgroundSC2/ScreenBackgroundSC2', 'ScreenNavigationSC2/ScreenNavigationSC2', 'ScreenForegroundSC2/ScreenForegroundSC2', 'ScreenArcade/ScreenArcade', 'ScreenArcadeJoin/ScreenArcadeJoin', 'ScreenBattlenet/ScreenBattlenet', 'ScreenScore/ScreenScore']}



Via 
http://localhost:6119/game 
(prio 2 -> to verify your are in a replay and not in game.)

E.g. 

#1 In an Arcade replay:
{"isReplay":true,"displayTime":0.0,"players":[{"id":1,"name":"agamja","type":"user","race":"Terr","result":"Undecided"},{"id":2,"name":"SkullBasher","type":"user","race":"Terr","result":"Undecided"},{"id":3,"name":"Soddit","type":"user","race":"Terr","result":"Undecided"},{"id":4,"name":"Thefck","type":"user","race":"Terr","result":"Undecided"},{"id":5,"name":"Sibola","type":"user","race":"Terr","result":"Undecided"},{"id":6,"name":"Fancore","type":"user","race":"Terr","result":"Undecided"},{"id":7,"name":"Donatien","type":"user","race":"Terr","result":"Undecided"},{"id":8,"name":"vicous","type":"user","race":"Terr","result":"Undecided"},{"id":9,"name":"BuRny","type":"user","race":"Terr","result":"Undecided"}]}

#2 In a Replay:
{"isReplay":false,"displayTime":0.0,"players":[{"id":1,"name":"BuRny","type":"user","race":"Prot","result":"Undecided"},{"id":2,"name":"A.I. 1 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":3,"name":"A.I. 2 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":4,"name":"A.I. 3 (Very Easy)","type":"computer","race":"random","result":"Undecided"}]}

#3 2v2 In game: (output of http://localhost:6119/game )
{"isReplay":false,"displayTime":1.0,"players":[{"id":1,"name":"BuRny","type":"user","race":"Prot","result":"Undecided"},{"id":2,"name":"A.I. 1 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":3,"name":"A.I. 2 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":4,"name":"A.I. 3 (Very Easy)","type":"computer","race":"random","result":"Undecided"}]}

    2v2 In Replay: (output of http://localhost:6119/game) 
{"isReplay":true,"displayTime":6.0,"players":[{"id":1,"name":"BuRny","type":"user","race":"Prot","result":"Undecided"},{"id":2,"name":"A.I. 1 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":3,"name":"A.I. 2 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":4,"name":"A.I. 3 (Very Easy)","type":"computer","race":"random","result":"Undecided"}]}

#4 3v3 In game:(output of http://localhost:6119/game)
{"isReplay":false,"displayTime":0.0,"players":[{"id":1,"name":"BuRny","type":"user","race":"Prot","result":"Undecided"},{"id":2,"name":"A.I. 1 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":3,"name":"A.I. 2 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":4,"name":"A.I. 3 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":5,"name":"A.I. 4 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":6,"name":"A.I. 5 (Very Easy)","type":"computer","race":"random","result":"Undecided"}]}

    3v3 In Replay: (output of http://localhost:6119/game)
{"isReplay":true,"displayTime":0.0,"players":[{"id":1,"name":"BuRny","type":"user","race":"Prot","result":"Undecided"},{"id":2,"name":"A.I. 1 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":3,"name":"A.I. 2 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":4,"name":"A.I. 3 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":5,"name":"A.I. 4 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":6,"name":"A.I. 5 (Very Easy)","type":"computer","race":"random","result":"Undecided"}]}

#5  4v4 In game: (output of http://localhost:6119/game)
{"isReplay":false,"displayTime":4.0,"players":[{"id":1,"name":"BuRny","type":"user","race":"Prot","result":"Undecided"},{"id":2,"name":"A.I. 1 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":3,"name":"A.I. 2 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":4,"name":"A.I. 3 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":5,"name":"A.I. 4 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":6,"name":"A.I. 5 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":7,"name":"A.I. 6 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":8,"name":"A.I. 7 (Very Easy)","type":"computer","race":"random","result":"Undecided"}]}

    4v4 Replay: (output of http://localhost:6119/game)
{"isReplay":true,"displayTime":4.0,"players":[{"id":1,"name":"BuRny","type":"user","race":"Prot","result":"Undecided"},{"id":2,"name":"A.I. 1 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":3,"name":"A.I. 2 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":4,"name":"A.I. 3 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":5,"name":"A.I. 4 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":6,"name":"A.I. 5 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":7,"name":"A.I. 6 (Very Easy)","type":"computer","race":"random","result":"Undecided"},{"id":8,"name":"A.I. 7 (Very Easy)","type":"computer","race":"random","result":"Undecided"}]}

#6  In game Coop: (output of http://localhost:6119/game)
{"isReplay":false,"displayTime":4.0,"players":[{"id":1,"name":"BuRny","type":"user","race":"Terr","result":"Undecided"},{"id":2,"name":"propagare","type":"user","race":"Prot","result":"Undecided"},{"id":3,"name":"Amon's Forces","type":"computer","race":"Zerg","result":"Undecided"},{"id":4,"name":"Amon's Forces","type":"computer","race":"Zerg","result":"Undecided"},{"id":5,"name":"Amon's Forces","type":"computer","race":"random","result":"Undecided"},{"id":6,"name":"Amon's Forces","type":"computer","race":"random","result":"Undecided"},{"id":7,"name":"Amon's Forces","type":"computer","race":"random","result":"Undecided"}]}
  
     In game Coop: (output of http://localhost:6119/game)
{"activeScreens":[]}

It would be great to have also the possibility to detect if I am in or out tabbed of Starcraft (->Set scene) but I didn't found anything regarding to this in the API. 

There is no score screen for Coop. :(

**Comment by leigholiver** [comment]
To be honest I didn't even realise OBS had themes. Should be able to get a fix out this evening.

**Comment by propagare** [comment]
Theme 'Rachni' has btw the same problem.

**Comment by leigholiver** [comment]
[Try this release, should be better now.](url) Thanks for the report!
