### ISSUE TITLE
Loading Screen 

### ISSUE THREAD

**Issue by 2press** [leigholiver/OBS-SC2Switcher#11]
I am not sure if this is intended behavior or an issue:

When you use a "In Game" scene different from your "Replay" or "Observing" scene, the switcher will always switch to the "In Game" scene while in the loading screen, even if you are not actually playing, and only switch to the "Observing" Scene once the loading screen is over. 

P.S.: My username list was today once again filled with my username on my first start of v0.95.

**Comment by leigholiver** [comment]
Its about 50/50, you can tell from the api that the user is going into a game, but you cant tell if its a replay or who is in the game until the game actually begins. Personally I like the switch to the in game scene on the loading screen and thats how it ended up like it is. I could certainly make this an option if this would be helpful?

**Comment by 2press** [comment]
It's fine if this is how it's intended. I can work around it.

**Comment by leigholiver** [comment]
This is now an option as of v0.96
