### ISSUE TITLE
where is the "text soucre"?

### ISSUE THREAD

**Issue by leochang0506** [leigholiver/OBS-SC2Switcher#12]
i am not the english speaker. if there is offensive words, forgive me 

my problem is that there is seem no text of source of Score Tracker(i have give name of that),that
should auto made by system,right? but where is it? i cant find it.

i download the all files (sc2switcher.dll and newest files like xxxx.h, xxx.cpp,...etc.) and place them all in D:\obs-studio\obs-plugins\64bit(yes, my obs place is in D disk)

i open SC2switcher in the tools menue, i only set something in Score Tracker and click "Start" in the first menue. the set up is following.
https://imgur.com/lzmAfW6
and run a 1 game in sc2, the score will change, that is good, but i cant find the "text source" that named after "ig1".

that should automately produced a file by system, right? what is wrong i do?
pls give me some tips, thx

have a good day,sir

**Comment by leigholiver** [comment]
Hi, you must create the text source. If you name it "ig1", it will be updated by the plugin
Here are the some screenshots of the steps in english, I hope this helps you with the right options
https://i.imgur.com/DO5dSTA.png
https://i.imgur.com/r0eJ3qx.png

**Comment by leochang0506** [comment]
really thank you, sir
that really help me very much, i solve all the problem i met.
if one day i meet someone who need help,but i dont know him, i must help him actively.
thank the plugin u made, and the help u give, thx again, sincerely.
