### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by LaughNgamez** [leigholiver/OBS-SC2Switcher#13]
The plugin will not load for me: https://pastebin.com/dNVSAueC

This is after a windows re-install, I've had this issue before many times but never found a root cause.

18:55:23.780: LoadLibrary failed for '../../obs-plugins/64bit/sc2switcher.dll': The specified module could not be found.
18:55:23.780:  (126)
18:55:23.780: Module '../../obs-plugins/64bit/sc2switcher.dll' not loaded

**Comment by leigholiver** [comment]
Thanks for the report - does this usually happen after a windows reinstall? Or has this happened during regular use?
It looks like it could be due to a missing dependency - I will investigate this and update you.

**Comment by LaughNgamez** [comment]
It happened when I first started using the plugin, somehow it started working but I can't remember how honestly.

Now I've reset windows again the error is there even using my old configs/installs.

**Comment by leigholiver** [comment]
It looks like this is because i compiled this plugin with a really old setup, [try installing the 2013 redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=40784) and that should get it going again. I'll look into recompiling it with a newer version

**Comment by LaughNgamez** [comment]
Seems like that install did not fix it.

**Comment by leigholiver** [comment]
Ah interesting - my test was on a brand new windows 10 install with just obs and the recommended set of dependencies, and that got it working. Does anything different get put in the logs or just the same message?

**Comment by LaughNgamez** [comment]
After testing it 11 days later it seems to be working! Sorry for the late response
