### ISSUE TITLE
OBS 24.0.3 64-bit LoadLibrary failed

### ISSUE THREAD

**Issue by 2press** [leigholiver/OBS-SC2Switcher#14]
I have made fresh reinstall of Windows 10 and OBS 24.0.3 (64-bit, windows). However, the sc2switcher libary downloaded from the latest release 0.96 at <https://github.com/leigholiver/OBS-SC2Switcher/releases/tag/0.96> fails to load:
```
19:23:31.460: LoadLibrary failed for '../../obs-plugins/64bit/sc2switcher.dll': (null) (126)
19:23:31.460: Module '../../obs-plugins/64bit/sc2switcher.dll' not loaded
```
See the logfile:
[2020-03-05 19-23-29.txt](https://github.com/leigholiver/OBS-SC2Switcher/files/4294450/2020-03-05.19-23-29.txt)

**Comment by leigholiver** [comment]
Hi, could you try installing [this library](https://www.microsoft.com/en-us/download/details.aspx?id=40784) and seeing if that resolves the issue?

**Comment by 2press** [comment]
Hi, yes that resolves the issue. I am sorry for bothering you due not having read the instructions. Were these dependecies always needed?

**Comment by leigholiver** [comment]
No worries at all, It wasn't in the readme until after I saw your issue so thank you for the reminder!
It wasn't always required, I believe they stopped including that library with windows 10 at some point. Essentially the version of Visual Studio I compiled the plugin with is just too old now.
