### ISSUE TITLE
W/L counter doesn't update if player won't quit into the menu

### ISSUE THREAD

**Issue by rzarai** [leigholiver/OBS-SC2Switcher#15]
I'm not the one having the issue, and I'm writing on behalf of another player.

The issue is when you leave the match and you do not quit to the main menu but instead jump from the game into the replay the program doesn't update the counter.

In other words: there is a possibility to jump from the game right in the replay of that game at the moment the game ended, and if a player does that the program won't update the counter.

**Comment by leigholiver** [comment]
Hi, thanks for reporting the issue. I'll try to get this fixed as soon as I can but I don't currently have a setup to compile the plugin.

**Comment by leigholiver** [comment]
I've just released a new version which fixes this: https://github.com/leigholiver/OBS-SC2Switcher/releases/tag/0.98
