### ISSUE TITLE
Missing Sc2 screens to switch to in-game and Alt+tab out 

### ISSUE THREAD

**Issue by propagare** [leigholiver/OBS-SC2Switcher#2]
Hello,

are you maybe willing to extend your great tool to the status which the SC2 client can switch to as well? 

If so it would be also really great if you also find the possibility to detect if someone is in or out tabbed (ALT+Tab) of Starcraft 2 (-->Define a scene?) but I didn't found anything regarding to this in the API. 

These are all SC2 screens I found via http://localhost:6119/ui

1. Startup, loading and leaving Sc2
2. Login screen (name, region, password, offline)
3. In menu after Login (Home screen)
4. Campaign screen
5. Coop screen
6. Custom Games main screen
7. Multiplayer: Training, Versus AI, Unranked, Ranked and Testing (Ranked ladder screen)
8. Tournament screen
9. Custom game Lobby
10. Arcade screen (join)
11. Arcade screen (browse)
12. Arcade game Lobby
13. Collection screen
14. Replay browsing
15. Replay "Watch With Others" Lobby
16. Score screen after a Custom game
17. Score screen after a Multiplayer Ranked
18. Score screen after Arcade

These following are all screens I found via http://localhost:6119/game
which are additional needed to verify your are in a replay and not in game.

In an Arcade replay
In a Replay
2v2 In game: 
2v2 In Replay
3v3 In game
3v3 In Replay
4v4 In game
4v4 Replay
In game Coop

What do you think about this?  I could provide all necessary logical gates from the API client to filter for these status.

**Comment by leigholiver** [comment]
I considered it when I was building the plugin but I couldn't find many reasons you would want seperate scenes for all of these. I'm more interested in keeping things simple, easy to use, and as automated as possible. In my opinion having the scene change all the time doesn't look good, and having to enter your username etc (along with the possibility of collision as the names arent unique) is an extra pain i'd rather just avoid. 

There is a [commented section ](https://github.com/leigholiver/OBS-SC2Switcher/blob/master/auto-scene-switcher.cpp#L184) to indicate where you can add these in if you were interested in forking the project to include it. 

In regards to being tabbed in/out, I believe you need to check that through the windows api not the sc2 api.

**Comment by propagare** [comment]
Thanks for the hint with the Windows API and I totally agree with your baseline of having things as easy and as automated as possible. I will not fork your project because I know how time consuming this is. 

Nevertheless "I see" ~20 drop down menus like yours, filled or empty (to switch to a default screen or do nothing) filled with OBS studio scenes by the users! Maybe still in our days to come! :)

The ethical imperative says: Act in such a way that you have more room for actions after your decision. :)

Warm regards!
