### ISSUE TITLE
Repeatedly clicking on Start/Stop results in crash

### ISSUE THREAD

**Issue by propagare** [leigholiver/OBS-SC2Switcher#5]
Sometimes it doesn't crash but crashes when trying to leave/exit OBS Studio.

OBS Studio v21.1.1-2-g0dc9151d

This crash exists only when Starcraft 2 is running.

**Comment by leigholiver** [comment]
Thanks for the report- i'll look into this as soon as I can

**Comment by leigholiver** [comment]
This is fixed in the latest version
