### ISSUE TITLE
LoadLibrary failed

### ISSUE THREAD

**Issue by 2press** [leigholiver/OBS-SC2Switcher#6]
Hi, 
a friend of mine can't get the OBS-SC2Switcher to work as OBS fails to load the corresponding library:

`18:20:12.283: LoadLibrary failed for '../../obs-plugins/64bit/SC2SceneSwitcher.dll': (null) (193)`
`18:20:12.283: Module '../../obs-plugins/64bit/SC2SceneSwitcher.dll' not loaded`

See attached a complete log file: [2018-05-03_18-20-11.txt](https://github.com/leigholiver/OBS-SC2Switcher/files/1971776/2018-05-03_18-20-11.txt)

He has already tried to uninstall obs, delete all settings, and uninstall obs from scratch, but it doesn't help to solve this issue.

**Comment by leigholiver** [comment]
Could you ask them to delete `obs-plugins/64bit/SC2SceneSwitcher.dll`, [redownload the file from Releases](https://github.com/leigholiver/OBS-SC2Switcher/releases/download/0.6/sc2switcher.zip) and reinstall the plugin from the new download? 
[Error 193 is essentially complaining that the file is corrupt](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx#ERROR_BAD_EXE_FORMAT), but I havent been able to reproduce it showing (null) as the error message like that.

**Comment by 2press** [comment]
He has already done this multiple times - I can't reproduce this error myself either.

**Comment by 2press** [comment]
Could you recompile it?

**Comment by leigholiver** [comment]
Unfortunately I'm not able to at the moment, he could try the [0.7 release](https://github.com/leigholiver/OBS-SC2Switcher/releases/tag/0.7), which is exactly the same bar a small ui change.
This one is really bugging me!

**Comment by 2press** [comment]
Switching to the 0.7 release worked. I have created a pull request to change the download link in README.md.

**Comment by leigholiver** [comment]
Glad to hear its resolved. What an odd issue. Thanks for troubleshooting!
