### ISSUE TITLE
Ingame vs observer detection doesn't work properly 

### ISSUE THREAD

**Issue by 2press** [leigholiver/OBS-SC2Switcher#8]
In the latest version the detection of "Ingame" vs "Observing" is not working properly. At first it was working for me, but today it didn't work - although I was observing, the scene would switch to the "Ingame" scene instead of the "Observing" scene. My username was entered properly, but I noticed that this very username was listed ~20 times in the username list (I entered it manually only once). I would assume that this is related.

Here is the obs log file:
[2018-10-17 19-45-51.txt](https://github.com/leigholiver/OBS-SC2Switcher/files/2488974/2018-10-17.19-45-51.txt)

**Comment by leigholiver** [comment]
Thanks, I'll look into this as soon as I can. In the meantime it _should_ help to clear out the usernames list and add your username again.

**Comment by leigholiver** [comment]
Did clearing out the usernames help? I've put some fixes in the latest patch that should help stop duplicate or blank usernames ending up in the list, let me know if it helps!

**Comment by 2press** [comment]
Once this happened I changed the "Ingame" scene to match the "Observer" scene to circumvent this issue. So, even so I cleared the usernames, I can't tell you if it helped. Nevertheless, yesterday I observed that the list was filled again with the same username over and over.

I'll will install this fix, test it and let you know if it's working. Thank you for this fast fix!

**Comment by 2press** [comment]
The username list was once again filled with the same name over and over after just restarting OBS without even using the switcher.

**Comment by 2press** [comment]
This never happened again, I might have been using the old version.
