### ISSUE TITLE
Whenever the scene changes the switcher is activated

### ISSUE THREAD

**Issue by 2press** [leigholiver/OBS-SC2Switcher#9]
I have another issue with the current "upgraded" version of the switcher that is related to all of these "extra" scene that were added. Before there were only two states "ingame" and "out of game" and the switcher would only switch once, when the state would change. This would allow me to manually change the scene while being out of game. In the "upgraded" version of the switcher there are many different states related to all of these extra scene. I currently don't use any of these extra states/scenes, nevertheless every time I would change the state of SC2, e.g., by opening a lobby, the scene switcher would redo the switch to the "out of game" scene in OBS, even though I don't want it to switch again, as I manually selected another OBS scene to be shown.

So, simple request: Could you change the switcher so that it only considers the activated states when triggering a switch?

**Comment by leigholiver** [comment]
My apologies that the behaviour has changed - The way you are describing it is the way I intended for it to work. I'll take a look as soon as I can, thanks for bringing this to my attention and for your patience!

**Comment by leigholiver** [comment]
I've just pushed a patch that should fix this - let me know! Again, thanks for your patience with the issues.

**Comment by 2press** [comment]
I will test it and come back to you! Thanks for the fast response.

**Comment by 2press** [comment]
Seems to be working now as intended.
